version: '3'

services:
  postgresql:
    image: bitnami/postgresql
    container_name: pg
    ports:
      - 8080:5432
    volumes:
      - /db:/bitnami/postgresql
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=findapet
