POST http://localhost:3000/org/
Content-Type: application/json

{
  "name" : "mikael",
  "email" : "mikael@gmail.com",
  "password" : "samuel123456",
  "cep" : "62580970",
  "phone" : "11944685352"
}

###

POST http://localhost:3000/org/authenticate/
Content-Type: application/json

{
  "email" : "samuel@gmail.com",
  "password" : "samuel123456"
}

###
POST http://localhost:3000/pet/
Content-Type: application/json

{
  "orgId" : "1282cb25-e8f0-4cfc-9448-43f91f35c7bd",
  "name" : "doguinho",
  "description" : "come muito",
  "age" : "adult",
  "size" : "big",
  "category" : "dog",
  "energyLevel" : "high",
  "independencyLevel" : "small",
  "spaceRequirement" : "wide",
  "adoptionRequirements" : ["be a nice person", "rich"]
}

###
GET http://localhost:3000/pet/search/Barueri?energyLevel=high&size=small
Content-Type: application/json